{
  "$schema": "https://developers.cloudflare.com/pages/functions/wrangler-configuration/#schema",
  "name": "audit-iq",
  "compatibility_date": "2025-12-10",
  "pages_build_output_dir": ".vercel/output/static"
}
